language: php

php:
  # using major version aliases
  # aliased to a recent 7.0.x version
  - 7.0

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - ./vendor/bin/phplint

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml

script: ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml

matrix:
  fast_finish: true
